# Generated by Django 3.1 on 2021-09-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210911_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('Г', 'г'), ('КГ', 'кг'), ('ШТ', 'шт'), ('ЧЛ', 'ч. л'), ('СТЛ', 'ст. л'), ('МЛ', 'мл'), ('Л', 'л'), ('СТАКАН', 'стакан'), ('ДОЛЬКА', 'долька'), ('ВЕТОЧКА', 'веточка'), ('ГОРСТЬ', 'горсть'), ('ПУЧОК', 'пучок'), ('ЩЕПОТКА', 'щепотка'), ('ПОВКУСУ', 'по вкусу'), ('КУСОК', 'кусок'), ('БАНКА', 'банка'), ('УПАКОВКА', 'упаковка'), ('БАТОН', 'батон')], max_length=200, verbose_name='Единица Измерения'),
        ),
    ]
